### ISSUE TITLE
Tool Fails to Compile via pipx, pip or pip3

### ISSUE THREAD

**Issue by Librechain** [Dedaub/srcup#11]
The command that you all have in your `Readme.md` instructs users to download the py package for your tool (`srcup`) via the following command: `pipx install git+https://github.com/Dedaub/srcup#egg=srcup`. 

Each attempt that I made failed with the same error message indicating that there was an issue with grabbing & installing `crytic-compile`. The submodules are not here in this repository but I can see that its pointing to a fork that you all have under this same account managing this repo & others. 

I received the following error message for the broken portion of the install: 

```sh
git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet 'ssh://****@github.com/Dedaub/crytic-compile.git' /private/var/folders/wn/2tk660b947s1m_216mdzhv8h0000gn/T/pip-install-93qfa3em/crytic-compile_6aa1282a3f5e422a9fe5823a79d5cc22 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip
```

Not sure what the issue is or whether the error can be taken at face-value. I have some proposed solutions but management of these things isn't up to me. Looking forward to this being fixed so that I can try the `srcup` tool as a member of Dedaub. Excited to see what your static analysis + LLM-integrated fuzzing produces as a result.

**Comment by iliastsa** [comment]
Thanks for the report! The issue was that a git dependency was using the SSH URI instead of the more universal HTTP one. I've released a new version that uses the latter -- this should resolve the problem. Let me know if the problem persists :)
